# Generated by Django 5.2.3 on 2025-07-04
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(max_length=10, blank=True, null=True),
        ),
    ]
