# Generated by Django 5.2.3 on 2025-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Выберите один или несколько размеров через запятую (например: S,M,L)', max_length=100, verbose_name='Доступные размеры'),
        ),
    ]
