# Generated by Django 5.2.3 on 2025-07-08 14:44

import duzanda.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_size_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=duzanda.storage_backends.ProductImagesStorage(), upload_to='product_images/'),
        ),
    ]
